### PR TITLE
Feature ads logos and licensing

### PR DESCRIPTION
**Pull request by jonnybazookatone**
Added a page that contains the logos used by the ADS. The pull request is not final, and needs to be complete after some discussion. More specifically:

  1. What licensing do we want?
     Currently I have put the Creative Commons with Attribution license, which means anyone can copy, modify, redistribute, sell it, aslong as they attribute the author
  2. I have put the author as SAO/NASA, but I would expect @aholachek gets credit also - I guess this is stipulated in our contracts somewhere? @aaccomazzi?
  3. I have added download buttons, which would be nice if they were zip files that contain a set of sizes and background colors (if possible). Much like with github, it means you can use them out of the box asap, which is pretty cool.
  4. We can add more images, these are the ones that came to my mind. We could include things like the 'Classic' style image on the new UI.

This should close adsabs/bumblebee/issues/420

### CODE REVIEW

**Comment by aholachek** [comment]
so i should wait to merge this until we talk about it, right?

**Comment by aaccomazzi** [comment]
Just to clarify, there is no contractual specification regarding licensing.  So we should follow Smithsonian's general policy which is to use a license such as CC-BY (http://creativecommons.org/licenses/by/4.0/) for this content.  Since the logos were created by Alex as part of her work at SAO the copyright belongs to SAO with credit to Alex as the developer.

**Comment by aholachek** [comment]
Noo think of all the royalties I'm going to miss out on

**Comment by aaccomazzi** [comment]
I think it can be merged as is, given that Jonny specified the correct
CC-BY license already.

-- AA


On Tue, Oct 13, 2015 at 11:54 AM, Alex <notifications@github.com> wrote:

> Noo think of all the royalties I'm going to miss out on
>
> On Tue, Oct 13, 2015 at 11:06 AM, Alberto Accomazzi <
> notifications@github.com> wrote:
>
> > Just to clarify, there is no contractual specification regarding
> > licensing. So we should follow Smithsonian's general policy which is to
> use
> > a license such as CC-BY (http://creativecommons.org/licenses/by/4.0/)
> for
> > this content. Since the logos were created by Alex as part of her work at
> > SAO the copyright belongs to SAO with credit to Alex as the developer.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/adsabs/help/pull/16#issuecomment-147743514>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/adsabs/help/pull/16#issuecomment-147758102>.
>



-- 
Dr. Alberto Accomazzi
Program Manager
NASA Astrophysics Data System - http://ads.harvard.edu
Harvard-Smithsonian Center for Astrophysics - http://www.cfa.harvard.edu
60 Garden St, MS 83, Cambridge, MA 02138, USA

**Pull request merged**
